Description: >

    This template deploys the EventServices Dispatcher Lambda function, responsible to route all received events to all subscribers.

    Last Modified: 2018
    Author: Kiko Gatto 

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    EventIntakeURL:
        Description: The event intake queue URL, where events will be deleted after processed
        Type: String
    EventIntakeARN:
        Description: The event intake queue ARN, to authorize the Role
        Type: String
    CatchAllQueueURL:
        Description: The catch all queue URL, where all events will be sent to eventually
        Type: String
    CatchAllQueueARN:
        Description: The catch all queue ARN, to authorize the Role
        Type: String

Resources:
    DispatcherLambdaRole: 
        Type: AWS::IAM::Role
        Properties: 
            AssumeRolePolicyDocument: 
                Version: '2012-10-17'
                Statement: 
                - Effect: Allow
                  Principal: 
                      Service: lambda.amazonaws.com
                  Action: 
                       - sts:AssumeRole
            Path: '/'
            Policies: 
            - PolicyName: logs
              PolicyDocument: 
                  Statement: 
                  - Effect: Allow
                    Action: 
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    Resource: arn:aws:logs:*:*:*
            - PolicyName: IntakeQueue
              PolicyDocument: 
                  Statement: 
                  - Effect: Allow
                    Action: 
                    - sqs:DeleteMessage
                    Resource: !Ref EventIntakeARN
            - PolicyName: CatchAllQueue
              PolicyDocument: 
                  Statement: 
                  - Effect: Allow
                    Action: 
                    - sqs:SendMessage
                    Resource: !Ref CatchAllQueueARN

    DispatcherLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            Code: 
                S3Bucket: !Sub
                  - ${StackName}-events 
                  - { StackName: !Ref EnvironmentName }
                S3Key: "dispatcher.zip"

            Handler: index.handler
            MemorySize: 128
            Role: !Sub ${DispatcherLambdaRole.Arn}
            Runtime: nodejs6.10
            Timeout: 60
            Environment:
                Variables:
                    INTAKE_QUEUE_URL: !Ref EventIntakeURL
                    CATCHALL_QUEUE_URL: !Ref CatchAllQueueURL
Outputs: 

    DispatcherLambdaID: 
        Description: the ID for the DispatcherLambda
        Value: 
            Ref: "DispatcherLambda"
    DispatcherLambdaARN: 
        Description: the ARN for the DispatcherLambda
        Value: 
            Fn::GetAtt:
                - "DispatcherLambda"
                - "Arn"