AWSTemplateFormatVersion: 2010-09-09
Description: >
    This template deploys the EventsServices Intake pipeline.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

    DeadLetterQueue:
        Type: 'AWS::SQS::Queue'

    EventIntake:
        Type: 'AWS::SQS::Queue'
        Properties:
            VisibilityTimeout: 60
            RedrivePolicy:
                deadLetterTargetArn: !Sub '${DeadLetterQueue.Arn}'
                maxReceiveCount: 10

    EventInlet:
        Type: 'AWS::SNS::Topic'
        Properties:
          Subscription:
            - Endpoint: !GetAtt 
                - EventIntake
                - Arn
              Protocol: sqs
    
    mysqspolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
              Id: IntaKeQueuePolicy
              Version: '2012-10-17'
              Statement:
              - Sid: Allow-Inlet-SendMessage
                Effect: Allow
                Principal: "*"
                Action:
                - sqs:SendMessage
                Resource: !GetAtt 
                    - EventIntake
                    - Arn
            Queues:
            - !Ref EventIntake


Outputs: 
    EventInletTopicARN:
        Description: the ARN for the Inlet SNS
        Value: 
            Ref: "EventInlet"
    EventIntakeQueueURL: 
        Description: the URL for the Intake queue
        Value: 
            Ref: "EventIntake"
    EventIntakeQueueARN: 
        Description: the URL for the Intake queue
        Value: 
            Fn::GetAtt:
                - "EventIntake"
                - "Arn"
