AWSTemplateFormatVersion: 2010-09-09
Description: >
    This template deploys the EventsServices Intake pipeline.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

    DeadLetterQueue:
        Type: 'AWS::SQS::Queue'

    EventIntake:
        Type: 'AWS::SQS::Queue'
        Properties:
            VisibilityTimeout: 60
            RedrivePolicy:
                deadLetterTargetArn: !Sub '${DeadLetterQueue.Arn}'
                maxReceiveCount: 10

    EventInlet:
        Type: 'AWS::SNS::Topic'
        Properties:
          Subscription:
            - Endpoint: !GetAtt 
                - EventIntake
                - Arn
              Protocol: sqs

Outputs: 

    EventIntakeQueueURL: 
        Description: the URL for the Intake queue
        Value: 
            Ref: "EventIntake"
    EventIntakeQueueARN: 
        Description: the URL for the Intake queue
        Value: 
            Fn::GetAtt:
                - "EventIntake"
                - "Arn"