Description: >

    This template deploys the EventServices.

    Last Modified: 2018
    Author: Kiko Gatto 

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String


Resources:

    Intake:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 
                - https://s3.amazonaws.com/${StackName}-events/intake.yml 
                - { StackName: !Ref EnvironmentName }
            Parameters:
                EnvironmentName:    !Ref EnvironmentName
    Dispatcher:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 
                - https://s3.amazonaws.com/${StackName}-events/dispatcher.yml 
                - { StackName: !Ref EnvironmentName }
            Parameters:
                EnvironmentName:    !Ref EnvironmentName
                EventIntake:    !GetAtt Intake.Outputs.EventIntakeQueueURL
    # Listener:
    #     Type: AWS::CloudFormation::Stack
    #     Properties:
    #         TemplateURL: !Sub 
    #             - https://s3.amazonaws.com/${StackName}-events/listener.yml 
    #             - { StackName: !Ref EnvironmentName }
    #         Parameters:
    #             EnvironmentName:    !Ref EnvironmentName



