Description: >

    This template deploys the EventServices.

    Last Modified: 2018
    Author: Kiko Gatto 

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String


Resources:

    Publisher:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 
                - https://s3.amazonaws.com/${StackName}-events/publisher.yml 
                - { StackName: !Ref EnvironmentName }
            Parameters:
                EnvironmentName:    !Ref EnvironmentName

    Dispatcher:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 
                - https://s3.amazonaws.com/${StackName}-events/dispatcher.yml 
                - { StackName: !Ref EnvironmentName }
            Parameters:
                EnvironmentName:    !Ref EnvironmentName
                PublishedQueueURL:    !GetAtt Publisher.Outputs.PublishedQueueURL
                PublishedQueueARN:    !GetAtt Publisher.Outputs.PublishedQueueARN
                # CatchAllQueueURL:    !GetAtt CatchAll.Outputs.CatchAllQueueURL
                # CatchAllQueueARN:    !GetAtt CatchAll.Outputs.CatchAllQueueARN


    # Listener:
    #     Type: AWS::CloudFormation::Stack
    #     Properties:
    #         TemplateURL: !Sub 
    #             - https://s3.amazonaws.com/${StackName}-events/listener.yml 
    #             - { StackName: !Ref EnvironmentName }
    #         Parameters:
    #             EnvironmentName:    !Ref EnvironmentName
    #             EventIntakeURL:    !GetAtt Publisher.Outputs.PublishedQueueURL
    #             EventIntakeARN:    !GetAtt Publisher.Outputs.PublishedQueueARN
    #             DispatcherLambdaARN:    !GetAtt Dispatcher.Outputs.DispatcherLambdaARN

    # CatchAll:
    #     Type: AWS::CloudFormation::Stack
    #     Properties:
    #         TemplateURL: !Sub 
    #             - https://s3.amazonaws.com/${StackName}-events/catchAll.yml 
    #             - { StackName: !Ref EnvironmentName }
    #         Parameters:
    #             EnvironmentName:    !Ref EnvironmentName





    # Subscriber:
    #     Type: AWS::CloudFormation::Stack
    #     Properties:
    #         TemplateURL: !Sub 
    #             - https://s3.amazonaws.com/${StackName}-events/subscriber.yml 
    #             - { StackName: !Ref EnvironmentName }
    #         Parameters:
    #             EnvironmentName:    !Ref EnvironmentName
