Description: >

    This template deploys the EventServices.

    Last Modified: 2018
    Author: Kiko Gatto 

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String


Resources:

    Intake:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 
                - https://s3.amazonaws.com/${StackName}-events/intake.yml 
                - { StackName: !Ref EnvironmentName }
            Parameters:
                EnvironmentName:    !Ref EnvironmentName
    CatchAll:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 
                - https://s3.amazonaws.com/${StackName}-events/catchAll.yml 
                - { StackName: !Ref EnvironmentName }
            Parameters:
                EnvironmentName:    !Ref EnvironmentName

    Dispatcher:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 
                - https://s3.amazonaws.com/${StackName}-events/dispatcher.yml 
                - { StackName: !Ref EnvironmentName }
            Parameters:
                EnvironmentName:    !Ref EnvironmentName
                EventIntakeURL:    !GetAtt Intake.Outputs.EventIntakeQueueURL
                EventIntakeARN:    !GetAtt Intake.Outputs.EventIntakeQueueARN
                CatchAllQueueURL:    !GetAtt CatchAll.Outputs.CatchAllQueueURL
                CatchAllQueueARN:    !GetAtt CatchAll.Outputs.CatchAllQueueARN

    Listener:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub 
                - https://s3.amazonaws.com/${StackName}-events/listener.yml 
                - { StackName: !Ref EnvironmentName }
            Parameters:
                EnvironmentName:    !Ref EnvironmentName
                EventInletTopicARN: !GetAtt Intake.Outputs.EventInletTopicARN 
                EventIntakeURL:    !GetAtt Intake.Outputs.EventIntakeQueueURL
                EventIntakeARN:    !GetAtt Intake.Outputs.EventIntakeQueueARN
                DispatcherLambdaARN:    !GetAtt Dispatcher.Outputs.DispatcherLambdaARN



